name = "10xcards"
compatibility_flags = [ "nodejs_compat", "disable_nodejs_process_v2" ]
compatibility_date = "2025-10-14"
pages_build_output_dir = "dist"

[vars]
OPENROUTER_MODEL = "google/gemini-2.5-flash-lite"